### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by pizazzche** [NT795/a16rumor#2]
Hello, could you share the dataset with me?

**Comment by NT795** [comment]
> Hello, could you share the dataset with me?

Hi，you can find the dataset in the paper 'Detecting Rumors from Microblogs with Recurrent Neural Networks'.  The download link is http://alt.qcri.org/~wgao/data/rumdect.zip

**Comment by pizazzche** [comment]
Thank you very much.

**Comment by isspek** [comment]
Hi @NT795, the link for the dataset is invalid. Could you provide please updated link?

Many thanks

**Comment by Dbgsaoge** [comment]
save question as above  @NT795 , can you please provide the undated download link? Thanks a lot !
