### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pizazzche** [NT795/a16rumor#3]
Hello, when I run the code , 

for floatx in cur_x:
--->   temp_x.append(float(floatx))
new_x.append(temp_x)

there always is a bug which is 'ValueError: could not convert string to float '

So I have not found solution on the internet. Could you help me ?

**Comment by NT795** [comment]
> Hello, when I run the code ,
> 
> for floatx in cur_x:
> ---> temp_x.append(float(floatx))
> new_x.append(temp_x)
> 
> there always is a bug which is 'ValueError: could not convert string to float '
> 
> So I have not found solution on the internet. Could you help me ?

Hi, have you converted the Weibo text data to TFIDF value？
In fact, I haven't exactly reproduced the accuracy in this paper, maybe I made a mistake in data processing or my understanding of the article was wrong, but the code should work(with an over-fitting result, if I remember correctly), and maybe you could try writing a new piece of code based on this code.

**Comment by pizazzche** [comment]
Thank you.Oh, I have not converted the Weibo text data to TFIDF value. As for the code ,  I will have a try . Thank you again.

**Comment by NT795** [comment]
> Thank you.Oh, I have not converted the Weibo text data to TFIDF value. As for the code , I will have a try . Thank you again.

You're welcome. It's important to note that the code I ended up debugging mostly was in the rumor_sever folder (especially MultiGRU.py) so there might be some bugs or inconsistencies in the other files.
